"""Cards of the prompted baselines and the generated ``docs/source/pyhazards_prompted.rst`` page.

Prompted multimodal LLMs are not ``nn.Module`` models with a builder, parameter counts or oracle-tested
weights, so they are not in the model catalog (``pyhazards/model_cards``). Each SmokeBench model has a
card in ``pyhazards/prompted/cards/<name>.yaml`` with its citation, licence, the settings of the
authors' runs, the numbers SmokeBench reports and PyHazards' deviations; this module validates the
cards and renders them into one documentation page (``scripts/render_prompted_docs.py``).
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Literal, Optional, Sequence

import yaml
from pydantic import BaseModel, Field, model_validator

from .metrics import AREA_BIN_LABELS, CONTRAST_BIN_LABELS
from .prompts import PROMPTS, TASKS

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CARDS_DIR = Path(__file__).resolve().parent / "cards"
DOCS_PAGE_PATH = REPO_ROOT / "docs" / "source" / "pyhazards_prompted.rst"
GENERATED_MARKER = ".. This file is generated by scripts/render_prompted_docs.py. Do not edit by hand."

SMOKEBENCH_TITLE = "SmokeBench: Evaluating Multimodal Large Language Models for Wildfire Smoke Detection"
SMOKEBENCH_URL = "https://arxiv.org/abs/2512.11215"
SMOKEBENCH_CODE_URL = "https://github.com/SoraLink/MLLM"
SMOKEBENCH_CODE_COMMIT = "183cdca488e8c7afa5a254f86ac675cb98951c73"

_BIN_KEYS = {"area": list(AREA_BIN_LABELS) + ["Overall"], "contrast": list(CONTRAST_BIN_LABELS) + ["Overall"]}


class Citation(BaseModel):
    title: str
    url: str
    repo_url: Optional[str] = None


class TaskNumbers(BaseModel):
    """Numbers of one task as printed in the SmokeBench tables."""

    area: Optional[Dict[str, float]] = None
    contrast: Optional[Dict[str, float]] = None
    smoke_free: Optional[float] = None
    overall: Optional[float] = None
    tables: str

    @model_validator(mode="after")
    def check_bins(self) -> "TaskNumbers":
        for kind in ("area", "contrast"):
            values = getattr(self, kind)
            if values is not None and list(values) != _BIN_KEYS[kind]:
                raise ValueError(f"{kind} numbers must list {_BIN_KEYS[kind]} in order, got {list(values)}")
        return self


class SmokeBenchNumbers(BaseModel):
    classification: Optional[TaskNumbers] = None
    tile: Optional[TaskNumbers] = None
    grid: Optional[TaskNumbers] = None
    detection: Optional[TaskNumbers] = None


class PromptedCard(BaseModel):
    name: str
    order: int
    display_name: str
    model_id: str
    access: Literal["open weights", "API"]
    install_extra: str
    license: str
    paper: Citation
    model_url: str
    smokebench_tasks: List[str]
    smokebench_reported: SmokeBenchNumbers
    settings: List[str] = Field(default_factory=list)
    deviations: List[str] = Field(default_factory=list)
    notes: List[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def check_tasks(self) -> "PromptedCard":
        unknown = [task for task in self.smokebench_tasks if task not in TASKS]
        if unknown:
            raise ValueError(f"unknown SmokeBench tasks {unknown}")
        for task in self.smokebench_tasks:
            if getattr(self.smokebench_reported, task) is None:
                raise ValueError(f"card {self.name} lists task {task} without reported numbers")
        return self


def load_prompted_cards(cards_dir: Path = CARDS_DIR) -> List[PromptedCard]:
    cards: List[PromptedCard] = []
    for path in sorted(cards_dir.glob("*.yaml")):
        card = PromptedCard.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")) or {})
        if card.name != path.stem:
            raise ValueError(f"card file name must match its name: {path.name} vs {card.name}")
        cards.append(card)
    return sorted(cards, key=lambda card: (card.order, card.name))


def _fmt(value: Optional[float]) -> str:
    return "--" if value is None else f"{value:.3f}"


def _table(title: str, header: Sequence[str], rows: Sequence[Sequence[str]]) -> List[str]:
    lines = [f".. list-table:: {title}", "   :header-rows: 1", ""]
    for row in [list(header)] + [list(r) for r in rows]:
        lines.append(f"   * - {row[0]}")
        lines.extend(f"     - {cell}" for cell in row[1:])
    return lines + [""]


_TASK_TITLES = {
    "classification": "Smoke classification",
    "tile": "Tile-based localization",
    "grid": "Grid-based localization",
    "detection": "Smoke detection",
}

_PROTOCOL_LINES = [
    "Protocol",
    "--------",
    "",
    f"PyHazards implements the four tasks of `{SMOKEBENCH_TITLE} <{SMOKEBENCH_URL}>`_ (Qi, Li & Barnes,",
    "WACV 2026) on the SmokeBench images, :doc:`FIgLib frames with the SmokeyNet smoke boxes <datasets/figlib_smokebench>`",
    "(5,046 smoke images and 1,000 smoke-free images). A model sees one image (or one tile) and one",
    "prompt and answers in text; decoding temperature 0.5. The prompts are the paper's, verbatim:",
    "",
]

_SCORING_LINES = [
    "Metrics and scoring",
    "~~~~~~~~~~~~~~~~~~~",
    "",
    "- **Classification** -- accuracy, reported separately on the smoke images (paper Tables 1-2, per",
    "  smoke-area and Weber-contrast quintile) and on the smoke-free images (Table 3). An answer counts",
    "  as \"smoke\" iff it contains ``True``; every other answer, including unparseable ones, counts as",
    "  \"no smoke\" (the authors' script; the paper does not say).",
    "- **Tile** -- the 3 x 4 tiles are classified independently with the classification prompt (a tile is",
    "  positive iff its answer contains ``True`` or ``true``); per-image IoU of the predicted and",
    "  ground-truth tile sets, averaged over smoke images (mIoU, Tables 4-5).",
    "- **Grid** -- the image carries a numbered 5 x 5 grid; every integer in the answer is a predicted",
    "  cell (an answer without numbers predicts nothing, IoU 0); mIoU of the cell sets (Tables 6-7).",
    "- **Detection** -- the first ``[[...]]`` span is read as JSON boxes; anything unparseable is the box",
    "  ``[0, 0, 0, 0]``. Per image, the largest IoU between a predicted and a ground-truth box (pixel",
    "  coordinates of the original frame), averaged over smoke images (Table 8).",
    "- A tile or cell is ground-truth positive when it contains a pixel of a box (both box ends inclusive).",
    "- Smoke area is the area of the (single) box; Weber contrast is ``|I_box - I_frame| / I_frame`` on the",
    "  OpenCV grey image with a 20-pixel frame around the box. Reports bin results at the quintiles of",
    "  the 5,046 boxes: area ``(42, 4356], (4356, 11232], (11232, 28565], (28565, 83157], (83157, 2232020]``",
    "  and contrast ``(0, 0.0246], (0.0246, 0.0549], (0.0549, 0.0878], (0.0878, 0.13], (0.13, 0.728]``",
    "  (Q1 = Very Small / Very Low ... Q5 = Very Large / Very High). PyHazards' area and contrast values",
    "  for the 5,046 SmokeBench images give exactly these quintiles (contrast to the 3 printed digits).",
    "",
    "The paper defines the tasks, prompts, temperature, partitions and metrics. Where it is silent",
    "(answer parsing, cell geometry, contrast background, per-model input handling) PyHazards follows",
    f"the authors' evaluation script (`SoraLink/MLLM <{SMOKEBENCH_CODE_URL}>`_ at ``{SMOKEBENCH_CODE_COMMIT[:7]}``;",
    "no licence, so it is used only as a test oracle and nothing is copied). The oracle test",
    "``tests/oracle/test_smokebench_oracle.py`` runs that script's own functions against PyHazards'.",
    "",
]

_DEVIATION_LINES = [
    "Differences from the paper and the authors' script",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "",
    "- **Prompts.** The released script words the prompts slightly differently from the paper: the",
    "  classification prompt ends \"Do MUST not return any other words\"; the grid and detection prompts say",
    "  \"If you cannot find any smoke return empty list []\"; the detection prompt asks for \"bounding box",
    "  in the format[[x1, y1, x2, y2], ...]\" and ends \"without other wordsDo not return dict!\" (string",
    "  pieces joined without spaces). PyHazards sends the paper's text.",
    "- **Temperature.** The paper fixes it at 0.5; the released script never sets it, so the authors' runs",
    "  used each checkpoint's generation config (greedy for Idefics2 and InternVL3, temperature 1e-6 for",
    "  Qwen2.5-VL). PyHazards samples at 0.5; ``do_sample=False`` gives greedy decoding.",
    "- **Tile crops.** The script crops ``image[i*hb:(i+1)*wb, j*wb:(j+1)*hb]`` (height and width blocks",
    "  swapped), so on the 3072 x 2048 frames (1,994 of 5,046) tiles overlap or leave gaps, while the",
    "  paper describes non-overlapping tiles. ``protocol=\"paper\"`` (default) crops the paper's tiles;",
    "  ``protocol=\"reference_code\"`` reproduces the script.",
    "- **Edge cells.** The script maps a box reaching the last ``H % rows`` / ``W % cols`` pixels to a",
    "  non-existent row/column, i.e. to a wrong cell id (72 grid and 19 tile cases among the 5,046 boxes).",
    "  ``protocol=\"paper\"`` clamps to the last row/column; ``protocol=\"reference_code\"`` keeps the script's ids.",
    "- **Malformed boxes.** The script scores boxes with fewer than four numbers 0 and crashes on other",
    "  malformed values; PyHazards scores every malformed prediction (and a zero-union NaN IoU) 0 and",
    "  counts them in the report.",
    "- **Smoke-free images.** The authors' 1,000 smoke-free frames were drawn without a seed from all",
    "  FIgLib sequences and not released; PyHazards draws a seeded sample from the pre-ignition frames of",
    "  the 145 annotated sequences, so smoke-free accuracy is not the same sample as Table 3.",
    "- **Closed models.** No code was released for GPT-4o and Gemini-2.5 Pro (classification only);",
    "  the request layout is documented on their cards below.",
    "",
]


def render_prompted_page(cards: Sequence[PromptedCard]) -> str:
    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "Prompted VLM Baselines",
        "======================",
        "",
        "Zero-shot multimodal large language models used as wildfire-smoke detectors by prompting them",
        "with an image and a question. They are not trainable ``nn.Module`` models and are therefore not",
        "part of the :doc:`model catalog <pyhazards_models>`; ``pyhazards.prompted`` provides the",
        "SmokeBench protocol (prompts, image partitions, answer parsing, metrics, a resumable runner) and",
        "backends for the models SmokeBench evaluated: open-weight checkpoints through Hugging Face",
        "``transformers`` and closed models through their official Python clients.",
        "",
        "Install the optional dependencies of the backend you use (nothing is added to the core install):",
        "",
        ".. code-block:: bash",
        "",
        "    pip install \"pyhazards[prompted]\"          # Pillow + OpenCV: data, grid overlay, metrics",
        "    pip install \"pyhazards[prompted-hf]\"       # + transformers, accelerate, torchvision (Qwen2.5-VL, InternVL3, Idefics2)",
        "    pip install \"pyhazards[prompted-gemini]\"   # + google-genai (reads GEMINI_API_KEY)",
        "    pip install \"pyhazards[prompted-openai]\"   # + openai (reads OPENAI_API_KEY)",
        "",
    ]
    lines.extend(_PROTOCOL_LINES)
    for task in TASKS:
        title = _TASK_TITLES[task]
        if task == "tile":
            lines.extend([f"**{title}** -- the classification prompt on each tile of a 3 x 4 grid.", ""])
            continue
        suffix = " (on the image with the numbered 5 x 5 grid drawn on it)" if task == "grid" else ""
        lines.extend([f"**{title}**{suffix}:", "", ".. code-block:: text", "", f"    {PROMPTS[task]}", ""])
    lines.extend(_SCORING_LINES)
    lines.extend(_DEVIATION_LINES)
    lines.extend(
        [
            "Usage",
            "-----",
            "",
            ".. code-block:: python",
            "",
            "    from pyhazards.datasets.figlib_smokebench import FIgLibSmokeBench, download_smokebench",
            "    from pyhazards.prompted import build_backend, evaluate_smokebench",
            "",
            "    download_smokebench(\"data/figlib\")          # SmokeyNet boxes + 145 FIgLib sequences (~11.4 GB)",
            "    data = FIgLibSmokeBench(\"data/figlib\")      # 5,046 smoke + 1,000 sampled smoke-free frames",
            "    backend = build_backend(\"qwen2_5_vl_7b\")    # temperature 0.5, 448 x 448 input as in SmokeBench",
            "    report = evaluate_smokebench(backend, data, \"classification\", output_dir=\"runs/qwen7b_cls\")",
            "    print(report[\"metrics\"][\"accuracy_smoke\"], report[\"paper_reported\"])",
            "",
            "or from the command line:",
            "",
            ".. code-block:: bash",
            "",
            "    python -m pyhazards.prompted --backend qwen2_5_vl_7b --task classification \\",
            "        --root data/figlib --output runs/qwen7b_cls",
            "",
            "Any object with ``generate(image, prompt) -> str`` (a subclass of",
            "``pyhazards.prompted.PromptedBackend``) can be evaluated the same way.",
            "",
            "Models",
            "------",
            "",
        ]
    )
    lines.extend(
        _table(
            "SmokeBench models available as backends",
            ["Backend", "Model", "Access", "Licence", "Extra", "SmokeBench tasks"],
            [
                [
                    f"``{card.name}``",
                    f"`{card.display_name} <{card.model_url}>`__",
                    card.access,
                    card.license,
                    f"``{card.install_extra}``",
                    ", ".join(card.smokebench_tasks),
                ]
                for card in cards
            ],
        )
    )
    lines.extend(
        [
            "Unified-IO 2 and Grounding DINO (detection only in SmokeBench) are not included: they are a",
            "referring-expression model and an open-set detector driven without the SmokeBench prompts. Llama 4",
            "is not part of SmokeBench and has no published wildfire-smoke protocol here, so it is not included.",
            "",
        ]
    )
    for card in cards:
        lines.extend(_render_card(card))
    lines.extend(
        [
            "References",
            "----------",
            "",
            f"- Qi, T., Li, W., Barnes, N. `{SMOKEBENCH_TITLE} <{SMOKEBENCH_URL}>`_. WACV 2026.",
            "- Dewangan, A. et al. `FIgLib & SmokeyNet: Dataset and Deep Learning Model for Real-Time Wildland",
            "  Fire Smoke Detection <https://doi.org/10.3390/rs14041007>`_. Remote Sensing 14(4):1007, 2022.",
            "- HPWREN Fire Ignition images Library (FIgLib), https://www.hpwren.ucsd.edu/FIgLib/ (credit",
            "  https://www.hpwren.ucsd.edu/ in derivative work).",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _render_card(card: PromptedCard) -> List[str]:
    title = card.display_name
    lines = [title, "~" * len(title), ""]
    paper = f"`{card.paper.title} <{card.paper.url}>`_"
    if card.paper.repo_url:
        paper += f" (`code <{card.paper.repo_url}>`__)"
    lines.extend(
        [
            f"**Model paper:** {paper}.",
            "",
            f"**Backend:** ``build_backend(\"{card.name}\")`` -- ``{card.model_id}`` ({card.access}; licence: {card.license}).",
            "",
        ]
    )
    reported = card.smokebench_reported
    for task in TASKS:
        numbers = getattr(reported, task)
        if numbers is None:
            continue
        caption = f"SmokeBench {_TASK_TITLES[task].lower()} ({numbers.tables})"
        rows: List[List[str]] = []
        if numbers.area is not None:
            rows.append(["smoke area"] + [_fmt(numbers.area[key]) for key in _BIN_KEYS["area"]])
        if numbers.contrast is not None:
            rows.append(["Weber contrast"] + [_fmt(numbers.contrast[key]) for key in _BIN_KEYS["contrast"]])
        if rows:
            metric = "accuracy" if task == "classification" else "mIoU"
            header = [f"{metric} by quintile", "Q1 (lowest)", "Q2", "Q3", "Q4", "Q5 (highest)", "Overall"]
            lines.extend(_table(caption, header, rows))
        extra = []
        if numbers.smoke_free is not None:
            extra.append(f"accuracy on smoke-free images {_fmt(numbers.smoke_free)}")
        if numbers.overall is not None and not rows:
            extra.append(f"mIoU {_fmt(numbers.overall)}")
        if extra:
            lines.extend([f"{caption}: " + "; ".join(extra) + ".", ""])
    for heading, items in (("Settings of the SmokeBench runs", card.settings), ("Deviations", card.deviations), ("Notes", card.notes)):
        if items:
            lines.extend([f"**{heading}:**", ""])
            lines.extend(f"- {item}" for item in items)
            lines.append("")
    return lines


def rendered_prompted_docs(cards: Optional[Sequence[PromptedCard]] = None) -> Dict[Path, str]:
    cards = load_prompted_cards() if cards is None else cards
    return {DOCS_PAGE_PATH: render_prompted_page(cards)}


def sync_prompted_docs(check: bool = False) -> List[Path]:
    """Write the generated page (or, with ``check``, list the files that are out of date)."""
    changed: List[Path] = []
    for path, text in rendered_prompted_docs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            changed.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    return changed


__all__ = [
    "CARDS_DIR",
    "DOCS_PAGE_PATH",
    "PromptedCard",
    "load_prompted_cards",
    "render_prompted_page",
    "rendered_prompted_docs",
    "sync_prompted_docs",
]
