from __future__ import annotations

import inspect
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Set

import torch
import yaml
from pydantic import BaseModel, Field, model_validator


REPO_ROOT = Path(__file__).resolve().parent.parent
MODEL_CARDS_DIR = Path(__file__).resolve().parent / "model_cards"
DOCS_SOURCE_DIR = REPO_ROOT / "docs" / "source"
MODULE_DOCS_DIR = DOCS_SOURCE_DIR / "modules"
MODEL_PAGE_PATH = DOCS_SOURCE_DIR / "pyhazards_models.rst"
API_PAGE_PATH = DOCS_SOURCE_DIR / "api" / "pyhazards.models.rst"

GENERATED_MARKER = (
    ".. This file is generated by scripts/render_model_docs.py. Do not edit by hand."
)
MODEL_PR_MARKER = "<!-- pyhazards:model-pr -->"
MODEL_REVIEW_MARKER = "<!-- pyhazards:model-pr-review -->"

NON_CATALOG_MODELS = {
    "mlp",
    "cnn",
    "temporal",
}


class PaperReference(BaseModel):
    title: str
    url: str


class SmokeTensorSpec(BaseModel):
    shape: List[int]
    dtype: str = "float32"


class SmokeInputSpec(BaseModel):
    kind: str
    tensor: Optional[SmokeTensorSpec] = None
    mapping: Dict[str, SmokeTensorSpec] = Field(default_factory=dict)
    kwargs: Dict[str, SmokeTensorSpec] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_payload(self) -> "SmokeInputSpec":
        kind = self.kind.lower()
        if kind == "tensor" and self.tensor is None:
            raise ValueError("tensor smoke inputs require the 'tensor' field")
        if kind == "mapping" and not self.mapping:
            raise ValueError("mapping smoke inputs require the 'mapping' field")
        if kind == "kwargs" and not self.kwargs:
            raise ValueError("kwargs smoke inputs require the 'kwargs' field")
        if kind not in {"tensor", "mapping", "kwargs"}:
            raise ValueError("smoke input kind must be one of: tensor, mapping, kwargs")
        return self


class SmokeOutputSpec(BaseModel):
    kind: str = "tensor"
    shape: Optional[List[int]] = None
    shapes: List[List[int]] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_payload(self) -> "SmokeOutputSpec":
        kind = self.kind.lower()
        if kind == "tensor" and self.shape is None:
            raise ValueError("tensor smoke outputs require the 'shape' field")
        if kind == "sequence" and not self.shapes:
            raise ValueError("sequence smoke outputs require the 'shapes' field")
        if kind not in {"tensor", "sequence"}:
            raise ValueError("smoke output kind must be one of: tensor, sequence")
        return self


class SmokeTestSpec(BaseModel):
    task: str
    build_kwargs: Dict[str, Any] = Field(default_factory=dict)
    input: SmokeInputSpec
    expected_output: SmokeOutputSpec


class ModelCard(BaseModel):
    model_name: str
    display_name: str
    hazard: str
    source_file: str
    builder_name: str
    summary: str
    description: List[str]
    paper: PaperReference
    tasks: List[str]
    example: str
    notes: List[str] = Field(default_factory=list)
    aliases: List[str] = Field(default_factory=list)
    doc_slug: Optional[str] = None
    smoke_test: SmokeTestSpec

    @property
    def registry_names(self) -> List[str]:
        return [self.model_name] + list(self.aliases)

    @property
    def module_doc_name(self) -> str:
        return self.doc_slug or "models_{name}".format(name=self.model_name)

    @property
    def module_doc_path(self) -> Path:
        return MODULE_DOCS_DIR / "{name}.rst".format(name=self.module_doc_name)

    @property
    def source_path(self) -> Path:
        return REPO_ROOT / self.source_file


def load_model_cards(cards_dir: Path = MODEL_CARDS_DIR) -> List[ModelCard]:
    cards: List[ModelCard] = []
    seen_registry_names: Set[str] = set()
    for path in sorted(cards_dir.glob("*.y*ml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        card = ModelCard.model_validate(raw)
        if path.stem != card.model_name:
            raise ValueError(
                "Model card filename must match model_name: "
                "{path} vs {name}".format(path=path.name, name=card.model_name)
            )
        overlap = set(card.registry_names) & seen_registry_names
        if overlap:
            raise ValueError(
                "Duplicate model catalog names detected: {names}".format(
                    names=", ".join(sorted(overlap))
                )
            )
        seen_registry_names.update(card.registry_names)
        cards.append(card)
    return cards


def card_by_registry_name(cards: Sequence[ModelCard]) -> Dict[str, ModelCard]:
    mapping: Dict[str, ModelCard] = {}
    for card in cards:
        for name in card.registry_names:
            mapping[name] = card
    return mapping


def group_cards_by_hazard(cards: Sequence[ModelCard]) -> Dict[str, List[ModelCard]]:
    grouped: Dict[str, List[ModelCard]] = defaultdict(list)
    for card in cards:
        grouped[card.hazard].append(card)
    return {
        hazard: sorted(hazard_cards, key=lambda item: item.display_name.lower())
        for hazard, hazard_cards in sorted(grouped.items(), key=lambda item: item[0].lower())
    }


def _paper_sentence(card: ModelCard) -> str:
    return "See `{title} <{url}>`_.".format(
        title=card.paper.title,
        url=card.paper.url,
    )


def _single_line(text: str) -> str:
    return " ".join(text.split())


def _indent_block(text: str, prefix: str = "   ") -> str:
    lines = text.rstrip().splitlines()
    return "\n".join(prefix + line if line else prefix.rstrip() for line in lines)


def render_model_page(cards: Sequence[ModelCard]) -> str:
    grouped = group_cards_by_hazard(cards)
    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "Models",
        "===================",
        "",
        "Summary",
        "-------",
        "",
        "PyHazards provides a lightweight, extensible model architecture with:",
        "",
        "- Backbones for common data types: MLP (tabular), CNN patch encoder (raster), temporal encoder (time-series).",
        "- Task heads: classification, regression, segmentation.",
        "- A registry-driven builder so you can construct built-ins by name or register your own.",
        "- Hazard-focused implementations for wildfire, flood, earthquake, weather, and more.",
        "",
        "Model",
        "-----",
        "",
        "The public model catalog is generated from ``pyhazards/model_cards/*.yaml``.",
        "Add or update a model card to refresh the model tables and detail pages automatically.",
        "",
    ]

    for hazard, hazard_cards in grouped.items():
        lines.extend(
            [
                hazard,
                "~" * len(hazard),
                "",
                ".. list-table::",
                "   :widths: 30 70",
                "   :header-rows: 1",
                "   :class: dataset-list",
                "",
                "   * - Model",
                "     - Description",
            ]
        )
        for card in hazard_cards:
            lines.extend(
                [
                    "   * - :doc:`{name} <modules/{slug}>`".format(
                        name=card.display_name,
                        slug=card.module_doc_name,
                    ),
                    "     - {summary} {paper}".format(
                        summary=_single_line(card.summary).rstrip(".") + ".",
                        paper=_paper_sentence(card),
                    ),
                ]
            )
        lines.append("")

    lines.extend(
        [
            "Build and register custom model",
            "-------------------------------",
            "",
            "Build a built-in model",
            "~~~~~~~~~~~~~~~~~~~~~~",
            "",
            ".. code-block:: python",
            "",
            "    from pyhazards.models import build_model",
            "",
            "    model = build_model(",
            '        name="mlp",',
            '        task="classification",',
            "        in_dim=32,",
            "        out_dim=5,",
            "        hidden_dim=256,",
            "        depth=3,",
            "    )",
            "",
            "Register a custom model",
            "~~~~~~~~~~~~~~~~~~~~~~~",
            "",
            "Create a builder function that returns an ``nn.Module`` and register it with a name.",
            "The registry handles defaults and discoverability.",
            "",
            ".. code-block:: python",
            "",
            "    import torch.nn as nn",
            "    from pyhazards.models import register_model, build_model",
            "",
            "    def my_custom_builder(task: str, in_dim: int, out_dim: int, **kwargs) -> nn.Module:",
            '        hidden = kwargs.get("hidden_dim", 128)',
            "        layers = nn.Sequential(",
            "            nn.Linear(in_dim, hidden),",
            "            nn.ReLU(),",
            "            nn.Linear(hidden, out_dim),",
            "        )",
            "        return layers",
            "",
            '    register_model("my_mlp", my_custom_builder, defaults={"hidden_dim": 128})',
            "",
            '    model = build_model(name="my_mlp", task="regression", in_dim=16, out_dim=1)',
            "",
            "Design notes",
            "~~~~~~~~~~~~",
            "",
            "- Builders receive ``task`` plus any kwargs you pass; use this to switch heads internally if needed.",
            "- ``register_model`` stores optional defaults so you can keep CLI/configs minimal.",
            "- Models are plain PyTorch modules, so you can compose them with the ``Trainer`` or your own loops.",
            "",
            ".. toctree::",
            "   :maxdepth: 1",
            "   :hidden:",
            "",
        ]
    )
    for card in cards:
        lines.append("   modules/{slug}".format(slug=card.module_doc_name))

    lines.append("")
    return "\n".join(lines)


def render_api_page(cards: Sequence[ModelCard]) -> str:
    grouped = group_cards_by_hazard(cards)
    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "pyhazards.models package",
        "========================",
        "",
        "Model Catalog",
        "-------------",
        "",
        "This summary is generated from ``pyhazards/model_cards/*.yaml`` so the API index",
        "and the main model page stay aligned.",
        "",
    ]
    for hazard, hazard_cards in grouped.items():
        lines.extend([hazard, "~" * len(hazard), ""])
        for card in hazard_cards:
            lines.extend(
                [
                    ":doc:`{name} </modules/{slug}>`".format(
                        name=card.display_name,
                        slug=card.module_doc_name,
                    ),
                    "",
                    "{summary}".format(summary=_single_line(card.summary).rstrip(".") + "."),
                    "",
                ]
            )

    lines.extend(
        [
            "Submodules",
            "----------",
            "",
            "pyhazards.models.backbones module",
            "----------------------------------",
            "",
            ".. automodule:: pyhazards.models.backbones",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.heads module",
            "------------------------------",
            "",
            ".. automodule:: pyhazards.models.heads",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.builder module",
            "-------------------------------",
            "",
            ".. automodule:: pyhazards.models.builder",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.registry module",
            "--------------------------------",
            "",
            ".. automodule:: pyhazards.models.registry",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "Module contents",
            "---------------",
            "",
            ".. automodule:: pyhazards.models",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
        ]
    )
    return "\n".join(lines)


def render_module_page(card: ModelCard) -> str:
    title = card.display_name
    lines: List[str] = [
        GENERATED_MARKER,
        "",
        title,
        "=" * len(title),
        "",
        "Description",
        "-----------",
        "",
    ]
    for paragraph in card.description:
        lines.append(paragraph)
        lines.append("")

    lines.extend(
        [
            "Paper",
            "-----",
            "",
            _paper_sentence(card),
            "",
            "Registry Name",
            "-------------",
            "",
            "Primary entrypoint: ``{name}``".format(name=card.model_name),
            "",
        ]
    )

    if card.aliases:
        lines.append("Aliases: {aliases}".format(
            aliases=", ".join("``{name}``".format(name=name) for name in card.aliases)
        ))
        lines.append("")

    lines.extend(
        [
            "Supported Tasks",
            "---------------",
            "",
        ]
    )
    for task in card.tasks:
        lines.append("- ``{task}``".format(task=task))
    lines.append("")
    lines.extend(
        [
            "Example of how to use it",
            "------------------------",
            "",
            ".. code-block:: python",
            "",
            _indent_block(card.example),
            "",
        ]
    )

    if card.notes:
        lines.extend(["Notes", "-----", ""])
        for note in card.notes:
            lines.append("- {note}".format(note=note))
        lines.append("")

    return "\n".join(lines)


def rendered_docs(cards: Sequence[ModelCard]) -> Dict[Path, str]:
    targets: Dict[Path, str] = {
        MODEL_PAGE_PATH: render_model_page(cards),
        API_PAGE_PATH: render_api_page(cards),
    }
    for card in cards:
        targets[card.module_doc_path] = render_module_page(card)
    return targets


def sync_generated_docs(cards: Sequence[ModelCard], check: bool = False) -> List[Path]:
    changes: List[Path] = []
    targets = rendered_docs(cards)

    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            changes.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    managed_paths = set(targets.keys())
    for path in MODULE_DOCS_DIR.glob("models_*.rst"):
        if path in managed_paths or not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text:
            continue
        changes.append(path)
        if not check:
            path.unlink()

    return changes


def model_catalog_alignment_issues(cards: Sequence[ModelCard]) -> List[str]:
    from pyhazards.models import available_models

    issues: List[str] = []
    registered = set(available_models())
    for card in cards:
        for name in card.registry_names:
            if name not in registered:
                issues.append("Model '{name}' is documented but not registered.".format(name=name))
    return issues


def builder_contract_issues(card: ModelCard) -> List[str]:
    from pyhazards.models.registry import get_model_config

    issues: List[str] = []
    config = get_model_config(card.model_name)
    if config is None:
        return ["Model '{name}' is not registered.".format(name=card.model_name)]

    builder = config["builder"]
    if builder.__name__ != card.builder_name:
        issues.append(
            "Model card expects builder '{expected}' but registry uses '{actual}'.".format(
                expected=card.builder_name,
                actual=builder.__name__,
            )
        )

    params = inspect.signature(builder).parameters
    has_var_kwargs = any(
        parameter.kind == inspect.Parameter.VAR_KEYWORD
        for parameter in params.values()
    )
    if "task" not in params and not has_var_kwargs:
        issues.append(
            "Builder '{name}' must accept a 'task' argument or **kwargs.".format(
                name=builder.__name__
            )
        )
    if not has_var_kwargs:
        issues.append(
            "Builder '{name}' should accept **kwargs for registry compatibility.".format(
                name=builder.__name__
            )
        )
    return issues


def source_contract_issues(card: ModelCard) -> List[str]:
    issues: List[str] = []
    if not card.source_path.exists():
        return [
            "Documented source file does not exist: {path}".format(path=card.source_file)
        ]

    source = card.source_path.read_text(encoding="utf-8")
    if "ValueError" not in source or ("shape" not in source and "ndim" not in source):
        issues.append(
            "Source file '{path}' should include explicit input-shape validation with a clear error.".format(
                path=card.source_file
            )
        )
    return issues


def _dtype_for_name(dtype_name: str) -> torch.dtype:
    if not hasattr(torch, dtype_name):
        raise ValueError("Unsupported torch dtype in smoke test: {name}".format(name=dtype_name))
    dtype = getattr(torch, dtype_name)
    if not isinstance(dtype, torch.dtype):
        raise ValueError("Unsupported torch dtype in smoke test: {name}".format(name=dtype_name))
    return dtype


def _make_tensor(spec: SmokeTensorSpec) -> torch.Tensor:
    return torch.randn(*spec.shape, dtype=_dtype_for_name(spec.dtype))


def _prepare_smoke_input(spec: SmokeInputSpec) -> Any:
    kind = spec.kind.lower()
    if kind == "tensor":
        return _make_tensor(spec.tensor)
    if kind == "mapping":
        return {name: _make_tensor(tensor_spec) for name, tensor_spec in spec.mapping.items()}
    return {name: _make_tensor(tensor_spec) for name, tensor_spec in spec.kwargs.items()}


def _shape_of_output(output: Any) -> Any:
    if isinstance(output, torch.Tensor):
        return list(output.shape)
    if isinstance(output, (list, tuple)):
        return [_shape_of_output(item) for item in output]
    return type(output).__name__


def run_smoke_test(card: ModelCard) -> Dict[str, Any]:
    from pyhazards.models import build_model

    torch.manual_seed(0)
    model = build_model(
        name=card.model_name,
        task=card.smoke_test.task,
        **card.smoke_test.build_kwargs
    )
    model.eval()
    prepared = _prepare_smoke_input(card.smoke_test.input)
    with torch.no_grad():
        if card.smoke_test.input.kind.lower() == "tensor":
            output = model(prepared)
        elif card.smoke_test.input.kind.lower() == "mapping":
            output = model(prepared)
        else:
            output = model(**prepared)

    actual_shape = _shape_of_output(output)
    expected = card.smoke_test.expected_output
    if expected.kind.lower() == "tensor":
        ok = actual_shape == expected.shape
    else:
        ok = actual_shape == expected.shapes

    return {
        "ok": ok,
        "actual_shape": actual_shape,
        "expected_shape": expected.shape if expected.kind.lower() == "tensor" else expected.shapes,
        "summary": "{name}: output shape {actual}".format(
            name=card.model_name,
            actual=actual_shape,
        ),
    }


def touched_card_names(cards: Sequence[ModelCard], changed_files: Iterable[str]) -> List[str]:
    source_to_name = {
        str(card.source_file): card.model_name
        for card in cards
    }
    names: Set[str] = set()
    for path in changed_files:
        if path.startswith("pyhazards/model_cards/") and path.endswith((".yaml", ".yml")):
            names.add(Path(path).stem)
        if path in source_to_name:
            names.add(source_to_name[path])
    return sorted(name for name in names if name)
