from __future__ import annotations

import inspect
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Literal, Mapping, Optional, Sequence, Set

import torch
import yaml
from pydantic import BaseModel, Field, model_validator


REPO_ROOT = Path(__file__).resolve().parent.parent
MODEL_CARDS_DIR = Path(__file__).resolve().parent / "model_cards"
DOCS_SOURCE_DIR = REPO_ROOT / "docs" / "source"
MODULE_DOCS_DIR = DOCS_SOURCE_DIR / "modules"
MODEL_PAGE_PATH = DOCS_SOURCE_DIR / "pyhazards_models.rst"
API_PAGE_PATH = DOCS_SOURCE_DIR / "api" / "pyhazards.models.rst"

GENERATED_MARKER = (
    ".. This file is generated by scripts/render_model_docs.py. Do not edit by hand."
)
MODEL_PR_MARKER = "<!-- pyhazards:model-pr -->"
MODEL_REVIEW_MARKER = "<!-- pyhazards:model-pr-review -->"

NON_CATALOG_MODELS = {
    "mlp",
    "cnn",
    "temporal",
}

HAZARD_DISPLAY_ORDER = [
    "Wildfire",
    "Earthquake",
    "Flood",
    "Hurricane",
    "Tropical Cyclone",
]

CATALOG_STATUS_ORDER = [
    "core",
    "variant",
    "experimental",
]

CATALOG_STATUS_TITLES = {
    "core": "Core Baselines",
    "variant": "Variants and Additional Implementations",
    "experimental": "Experimental Adapters",
}

CATALOG_STATUS_SUMMARIES = {
    "core": "These entries count toward the current core public method set.",
    "variant": "These entries stay public, but they are grouped outside the core method count because they are same-paper variants or additional off-plan implementations.",
    "experimental": "These entries remain public as lightweight wrapper or prototype integrations and should not be counted as stable core methods.",
}


class PaperReference(BaseModel):
    title: str
    url: str


class SmokeTensorSpec(BaseModel):
    shape: List[int]
    dtype: str = "float32"


class SmokeInputSpec(BaseModel):
    kind: str
    tensor: Optional[SmokeTensorSpec] = None
    mapping: Dict[str, SmokeTensorSpec] = Field(default_factory=dict)
    kwargs: Dict[str, SmokeTensorSpec] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_payload(self) -> "SmokeInputSpec":
        kind = self.kind.lower()
        if kind == "tensor" and self.tensor is None:
            raise ValueError("tensor smoke inputs require the 'tensor' field")
        if kind == "mapping" and not self.mapping:
            raise ValueError("mapping smoke inputs require the 'mapping' field")
        if kind == "kwargs" and not self.kwargs:
            raise ValueError("kwargs smoke inputs require the 'kwargs' field")
        if kind not in {"tensor", "mapping", "kwargs"}:
            raise ValueError("smoke input kind must be one of: tensor, mapping, kwargs")
        return self


class SmokeOutputSpec(BaseModel):
    kind: str = "tensor"
    shape: Optional[List[int]] = None
    shapes: List[List[int]] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_payload(self) -> "SmokeOutputSpec":
        kind = self.kind.lower()
        if kind == "tensor" and self.shape is None:
            raise ValueError("tensor smoke outputs require the 'shape' field")
        if kind == "sequence" and not self.shapes:
            raise ValueError("sequence smoke outputs require the 'shapes' field")
        if kind not in {"tensor", "sequence"}:
            raise ValueError("smoke output kind must be one of: tensor, sequence")
        return self


class SmokeTestSpec(BaseModel):
    task: str
    build_kwargs: Dict[str, Any] = Field(default_factory=dict)
    input: SmokeInputSpec
    expected_output: SmokeOutputSpec


class ModelCard(BaseModel):
    model_name: str
    display_name: str
    hazard: str
    include_in_public_catalog: bool = True
    catalog_status: Literal["core", "variant", "experimental", "hidden"] = "core"
    family_key: Optional[str] = None
    family_label: Optional[str] = None
    source_file: str
    builder_name: str
    summary: str
    description: List[str]
    paper: PaperReference
    tasks: List[str]
    example: str
    notes: List[str] = Field(default_factory=list)
    aliases: List[str] = Field(default_factory=list)
    doc_slug: Optional[str] = None
    smoke_test: SmokeTestSpec

    @model_validator(mode="after")
    def validate_catalog_metadata(self) -> "ModelCard":
        if self.catalog_status == "hidden" and self.include_in_public_catalog:
            raise ValueError("hidden catalog_status requires include_in_public_catalog: false")
        if self.family_key and not self.family_label:
            raise ValueError("family_key requires family_label")
        if self.family_label and not self.family_key:
            raise ValueError("family_label requires family_key")
        return self

    @property
    def registry_names(self) -> List[str]:
        return [self.model_name] + list(self.aliases)

    @property
    def module_doc_name(self) -> str:
        return self.doc_slug or "models_{name}".format(name=self.model_name)

    @property
    def module_doc_path(self) -> Path:
        return MODULE_DOCS_DIR / "{name}.rst".format(name=self.module_doc_name)

    @property
    def source_path(self) -> Path:
        return REPO_ROOT / self.source_file


def load_model_cards(cards_dir: Path = MODEL_CARDS_DIR) -> List[ModelCard]:
    cards: List[ModelCard] = []
    seen_registry_names: Set[str] = set()
    for path in sorted(cards_dir.glob("*.y*ml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        card = ModelCard.model_validate(raw)
        if path.stem != card.model_name:
            raise ValueError(
                "Model card filename must match model_name: "
                "{path} vs {name}".format(path=path.name, name=card.model_name)
            )
        overlap = set(card.registry_names) & seen_registry_names
        if overlap:
            raise ValueError(
                "Duplicate model catalog names detected: {names}".format(
                    names=", ".join(sorted(overlap))
                )
            )
        seen_registry_names.update(card.registry_names)
        cards.append(card)
    return cards


def card_by_registry_name(cards: Sequence[ModelCard]) -> Dict[str, ModelCard]:
    mapping: Dict[str, ModelCard] = {}
    for card in cards:
        for name in card.registry_names:
            mapping[name] = card
    return mapping


def group_cards_by_hazard(cards: Sequence[ModelCard]) -> Dict[str, List[ModelCard]]:
    grouped: Dict[str, List[ModelCard]] = defaultdict(list)
    for card in cards:
        grouped[card.hazard].append(card)

    def order_key(hazard: str) -> tuple[int, str]:
        if hazard in HAZARD_DISPLAY_ORDER:
            return (HAZARD_DISPLAY_ORDER.index(hazard), hazard.lower())
        return (len(HAZARD_DISPLAY_ORDER), hazard.lower())

    return {
        hazard: sorted(hazard_cards, key=lambda item: item.display_name.lower())
        for hazard, hazard_cards in sorted(grouped.items(), key=lambda item: order_key(item[0]))
    }


def public_catalog_cards(cards: Sequence[ModelCard]) -> List[ModelCard]:
    return [card for card in cards if card.include_in_public_catalog]


def _cards_by_status(cards: Sequence[ModelCard]) -> Dict[str, List[ModelCard]]:
    grouped: Dict[str, List[ModelCard]] = {status: [] for status in CATALOG_STATUS_ORDER}
    for card in cards:
        if card.catalog_status in grouped:
            grouped[card.catalog_status].append(card)
    for status in grouped:
        grouped[status] = sorted(grouped[status], key=lambda item: item.display_name.lower())
    return grouped


def _grouped_catalog_entries(cards: Sequence[ModelCard]) -> List[List[ModelCard]]:
    entries: List[List[ModelCard]] = []
    family_seen: Set[str] = set()
    ordered_cards = sorted(cards, key=lambda item: item.display_name.lower())
    for card in ordered_cards:
        if card.family_key:
            if card.family_key in family_seen:
                continue
            family_seen.add(card.family_key)
            family_cards = [
                member
                for member in ordered_cards
                if member.family_key == card.family_key
            ]
            entries.append(family_cards)
            continue
        entries.append([card])
    return entries


def _paper_sentence(card: ModelCard) -> str:
    return "See `{title} <{url}>`_.".format(
        title=card.paper.title,
        url=card.paper.url,
    )


def _single_line(text: str) -> str:
    return " ".join(text.split())


def _indent_block(text: str, prefix: str = "   ") -> str:
    lines = text.rstrip().splitlines()
    return "\n".join(prefix + line if line else prefix.rstrip() for line in lines)


def _doc_link(card: ModelCard, absolute: bool = False) -> str:
    target = "/modules/{slug}".format(slug=card.module_doc_name) if absolute else "modules/{slug}".format(slug=card.module_doc_name)
    return ":doc:`{name} <{target}>`".format(
        name=card.display_name,
        target=target,
    )


def _family_row_name(cards: Sequence[ModelCard]) -> str:
    label = cards[0].family_label or cards[0].display_name
    return label


def _family_row_summary(cards: Sequence[ModelCard], status: str, absolute_links: bool = False) -> str:
    members = ", ".join(
        _doc_link(card, absolute=absolute_links)
        for card in cards
    )
    if status == "variant":
        prefix = (
            "Family variants: {members}. These entries come from the same source "
            "paper and are grouped here so they do not count as separate core "
            "methods."
        )
    else:
        prefix = "Family members: {members}."
    return "{prefix} {paper}".format(
        prefix=prefix.format(members=members),
        paper=_paper_sentence(cards[0]),
    )


def _row_name(cards: Sequence[ModelCard]) -> str:
    if len(cards) == 1:
        return _doc_link(cards[0])
    return _family_row_name(cards)


def _row_summary(cards: Sequence[ModelCard], status: str, absolute_links: bool = False) -> str:
    if len(cards) == 1:
        card = cards[0]
        return "{summary} {paper}".format(
            summary=_single_line(card.summary).rstrip(".") + ".",
            paper=_paper_sentence(card),
        )
    return _family_row_summary(cards, status, absolute_links=absolute_links)


def render_model_page(cards: Sequence[ModelCard]) -> str:
    grouped = group_cards_by_hazard(public_catalog_cards(cards))
    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "Models",
        "===================",
        "",
        "Overview",
        "--------",
        "",
        "Use this page to browse the public model catalog, compare supported",
        "model implementations, and see how registered models are constructed",
        "through the shared PyHazards registry.",
        "",
        "Model Catalog",
        "-------------",
        "",
        "The public catalog below is generated from ``pyhazards/model_cards/*.yaml``.",
        "Use this page for model discovery and quick registry lookup. Core baselines,",
        "variants, and experimental adapters are listed separately so the public",
        "catalog does not over-count same-paper variants as independent methods.",
        "Use :doc:`appendix_a_coverage` for the audited roadmap gap list,",
        ":doc:`pyhazards_benchmarks` for current runnable evaluator coverage, and",
        "the Implementation Guide for contributor workflow details.",
        "",
    ]

    for hazard, hazard_cards in grouped.items():
        lines.extend([hazard, "~" * len(hazard), ""])
        cards_by_status = _cards_by_status(hazard_cards)
        for status in CATALOG_STATUS_ORDER:
            title = CATALOG_STATUS_TITLES[status]
            lines.extend([title, "+" * len(title), "", CATALOG_STATUS_SUMMARIES[status], ""])
            status_cards = cards_by_status[status]
            if not status_cards:
                if status == "core":
                    lines.extend(
                        [
                            "No core public methods are currently implemented for this",
                            "hazard family. See :doc:`appendix_a_coverage` for the audited",
                            "missing baseline and benchmark adapters.",
                            "",
                        ]
                    )
                else:
                    lines.append("None.")
                    lines.append("")
                continue

            lines.extend(
                [
                    ".. list-table::",
                    "   :widths: 30 70",
                    "   :header-rows: 1",
                    "   :class: dataset-list",
                    "",
                    "   * - Model",
                    "     - Description",
                ]
            )
            for entry in _grouped_catalog_entries(status_cards):
                lines.extend(
                    [
                        "   * - {name}".format(name=_row_name(entry)),
                        "     - {summary}".format(summary=_row_summary(entry, status)),
                    ]
                )
            lines.append("")
        lines.append("")

    lines.extend(
        [
            "Using the Registry",
            "------------------",
            "",
            "Build a Registered Model",
            "~~~~~~~~~~~~~~~~~~~~~~~~",
            "",
            ".. code-block:: python",
            "",
            "    from pyhazards.models import build_model",
            "",
            "    model = build_model(",
            '        name="mlp",',
            '        task="classification",',
            "        in_dim=32,",
            "        out_dim=5,",
            "        hidden_dim=256,",
            "        depth=3,",
            "    )",
            "",
            "Register a Custom Model",
            "~~~~~~~~~~~~~~~~~~~~~~~",
            "",
            "Register a builder function that returns an ``nn.Module`` so users can",
            "load the model by name through the shared registry.",
            "",
            ".. code-block:: python",
            "",
            "    import torch.nn as nn",
            "    from pyhazards.models import register_model, build_model",
            "",
            "    def my_custom_builder(task: str, in_dim: int, out_dim: int, **kwargs) -> nn.Module:",
            '        hidden = kwargs.get("hidden_dim", 128)',
            "        layers = nn.Sequential(",
            "            nn.Linear(in_dim, hidden),",
            "            nn.ReLU(),",
            "            nn.Linear(hidden, out_dim),",
            "        )",
            "        return layers",
            "",
            '    register_model("my_mlp", my_custom_builder, defaults={"hidden_dim": 128})',
            "",
            '    model = build_model(name="my_mlp", task="regression", in_dim=16, out_dim=1)',
            "",
            "Notes",
            "~~~~~",
            "",
            "- Builders receive ``task`` plus any kwargs you pass.",
            "- ``register_model`` stores optional defaults so configs can stay small.",
            "- Models are plain PyTorch modules and work with ``Trainer`` or custom loops.",
            "",
            ".. toctree::",
            "   :maxdepth: 1",
            "   :hidden:",
            "",
        ]
    )
    for card in public_catalog_cards(cards):
        lines.append("   modules/{slug}".format(slug=card.module_doc_name))

    lines.append("")
    return "\n".join(lines)


def render_api_page(cards: Sequence[ModelCard]) -> str:
    grouped = group_cards_by_hazard(public_catalog_cards(cards))
    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "pyhazards.models package",
        "========================",
        "",
        "Model Catalog",
        "-------------",
        "",
        "This page mirrors the public model catalog and then lists the package",
        "submodules for API lookup.",
        "",
    ]
    for hazard, hazard_cards in grouped.items():
        lines.extend([hazard, "~" * len(hazard), ""])
        cards_by_status = _cards_by_status(hazard_cards)
        for status in CATALOG_STATUS_ORDER:
            title = CATALOG_STATUS_TITLES[status]
            lines.extend([title, "+" * len(title), ""])
            status_cards = cards_by_status[status]
            if not status_cards:
                if status == "core":
                    lines.extend(
                        [
                            "No core public methods are currently implemented for this hazard family.",
                            "",
                        ]
                    )
                else:
                    lines.extend(["None.", ""])
                continue
            for entry in _grouped_catalog_entries(status_cards):
                lines.extend(
                    [
                        "{name}".format(
                            name=(
                                _doc_link(entry[0], absolute=True)
                                if len(entry) == 1
                                else _family_row_name(entry)
                            )
                        ),
                        "",
                        "{summary}".format(summary=_row_summary(entry, status, absolute_links=True)),
                        "",
                    ]
                )

    lines.extend(
        [
            "Submodules",
            "----------",
            "",
            "pyhazards.models.backbones module",
            "----------------------------------",
            "",
            ".. automodule:: pyhazards.models.backbones",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.heads module",
            "------------------------------",
            "",
            ".. automodule:: pyhazards.models.heads",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.builder module",
            "-------------------------------",
            "",
            ".. automodule:: pyhazards.models.builder",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.registry module",
            "--------------------------------",
            "",
            ".. automodule:: pyhazards.models.registry",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "Module contents",
            "---------------",
            "",
            ".. automodule:: pyhazards.models",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
        ]
    )
    return "\n".join(lines)


def render_module_page(card: ModelCard) -> str:
    title = card.display_name
    lines: List[str] = [
        GENERATED_MARKER,
        "",
    ]
    if not card.include_in_public_catalog:
        lines.extend([":orphan:", ""])

    lines.extend(
        [
            title,
            "=" * len(title),
            "",
            "Description",
            "-----------",
            "",
        ]
    )
    for paragraph in card.description:
        lines.append(paragraph)
        lines.append("")

    lines.extend(
        [
            "Paper",
            "-----",
            "",
            _paper_sentence(card),
            "",
            "Catalog Status",
            "--------------",
            "",
            "Status: ``{status}``".format(status=card.catalog_status),
            "",
            "Registry Name",
            "-------------",
            "",
            "Primary entrypoint: ``{name}``".format(name=card.model_name),
            "",
        ]
    )

    if card.family_label:
        lines.append("Family: ``{family}``".format(family=card.family_label))
        lines.append("")

    if card.aliases:
        lines.append("Aliases: {aliases}".format(
            aliases=", ".join("``{name}``".format(name=name) for name in card.aliases)
        ))
        lines.append("")

    lines.extend(
        [
            "Supported Tasks",
            "---------------",
            "",
        ]
    )
    for task in card.tasks:
        lines.append("- ``{task}``".format(task=task))
    lines.append("")
    lines.extend(
        [
            "Example of how to use it",
            "------------------------",
            "",
            ".. code-block:: python",
            "",
            _indent_block(card.example),
            "",
        ]
    )

    if card.notes:
        lines.extend(["Notes", "-----", ""])
        for note in card.notes:
            lines.append("- {note}".format(note=note))
        lines.append("")

    return "\n".join(lines)


def rendered_docs(cards: Sequence[ModelCard]) -> Dict[Path, str]:
    targets: Dict[Path, str] = {
        MODEL_PAGE_PATH: render_model_page(cards),
        API_PAGE_PATH: render_api_page(cards),
    }
    for card in cards:
        targets[card.module_doc_path] = render_module_page(card)
    return targets


def sync_generated_docs(cards: Sequence[ModelCard], check: bool = False) -> List[Path]:
    changes: List[Path] = []
    targets = rendered_docs(cards)

    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            changes.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    managed_paths = set(targets.keys())
    for path in MODULE_DOCS_DIR.glob("models_*.rst"):
        if path in managed_paths or not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text:
            continue
        changes.append(path)
        if not check:
            path.unlink()

    return changes


def model_catalog_alignment_issues(cards: Sequence[ModelCard]) -> List[str]:
    from pyhazards.models import available_models

    issues: List[str] = []
    registered = set(available_models())
    for card in cards:
        for name in card.registry_names:
            if name not in registered:
                issues.append("Model '{name}' is documented but not registered.".format(name=name))
    return issues


def builder_contract_issues(card: ModelCard) -> List[str]:
    from pyhazards.models.registry import get_model_config

    issues: List[str] = []
    config = get_model_config(card.model_name)
    if config is None:
        return ["Model '{name}' is not registered.".format(name=card.model_name)]

    builder = config["builder"]
    if builder.__name__ != card.builder_name:
        issues.append(
            "Model card expects builder '{expected}' but registry uses '{actual}'.".format(
                expected=card.builder_name,
                actual=builder.__name__,
            )
        )

    params = inspect.signature(builder).parameters
    has_var_kwargs = any(
        parameter.kind == inspect.Parameter.VAR_KEYWORD
        for parameter in params.values()
    )
    if "task" not in params and not has_var_kwargs:
        issues.append(
            "Builder '{name}' must accept a 'task' argument or **kwargs.".format(
                name=builder.__name__
            )
        )
    if not has_var_kwargs:
        issues.append(
            "Builder '{name}' should accept **kwargs for registry compatibility.".format(
                name=builder.__name__
            )
        )
    return issues


def source_contract_issues(card: ModelCard) -> List[str]:
    issues: List[str] = []
    if not card.source_path.exists():
        return [
            "Documented source file does not exist: {path}".format(path=card.source_file)
        ]

    source = card.source_path.read_text(encoding="utf-8")
    if "ValueError" not in source or ("shape" not in source and "ndim" not in source):
        issues.append(
            "Source file '{path}' should include explicit input-shape validation with a clear error.".format(
                path=card.source_file
            )
        )
    return issues


def _dtype_for_name(dtype_name: str) -> torch.dtype:
    if not hasattr(torch, dtype_name):
        raise ValueError("Unsupported torch dtype in smoke test: {name}".format(name=dtype_name))
    dtype = getattr(torch, dtype_name)
    if not isinstance(dtype, torch.dtype):
        raise ValueError("Unsupported torch dtype in smoke test: {name}".format(name=dtype_name))
    return dtype


def _make_tensor(spec: SmokeTensorSpec) -> torch.Tensor:
    return torch.randn(*spec.shape, dtype=_dtype_for_name(spec.dtype))


def _prepare_smoke_input(spec: SmokeInputSpec) -> Any:
    kind = spec.kind.lower()
    if kind == "tensor":
        return _make_tensor(spec.tensor)
    if kind == "mapping":
        return {name: _make_tensor(tensor_spec) for name, tensor_spec in spec.mapping.items()}
    return {name: _make_tensor(tensor_spec) for name, tensor_spec in spec.kwargs.items()}


def _shape_of_output(output: Any) -> Any:
    if isinstance(output, torch.Tensor):
        return list(output.shape)
    if isinstance(output, (list, tuple)):
        return [_shape_of_output(item) for item in output]
    return type(output).__name__


def run_smoke_test(card: ModelCard) -> Dict[str, Any]:
    from pyhazards.models import build_model

    torch.manual_seed(0)
    model = build_model(
        name=card.model_name,
        task=card.smoke_test.task,
        **card.smoke_test.build_kwargs
    )
    model.eval()
    prepared = _prepare_smoke_input(card.smoke_test.input)
    with torch.no_grad():
        if card.smoke_test.input.kind.lower() == "tensor":
            output = model(prepared)
        elif card.smoke_test.input.kind.lower() == "mapping":
            output = model(prepared)
        else:
            output = model(**prepared)

    actual_shape = _shape_of_output(output)
    expected = card.smoke_test.expected_output
    if expected.kind.lower() == "tensor":
        ok = actual_shape == expected.shape
    else:
        ok = actual_shape == expected.shapes

    return {
        "ok": ok,
        "actual_shape": actual_shape,
        "expected_shape": expected.shape if expected.kind.lower() == "tensor" else expected.shapes,
        "summary": "{name}: output shape {actual}".format(
            name=card.model_name,
            actual=actual_shape,
        ),
    }


def touched_card_names(cards: Sequence[ModelCard], changed_files: Iterable[str]) -> List[str]:
    source_to_name = {
        str(card.source_file): card.model_name
        for card in cards
    }
    names: Set[str] = set()
    for path in changed_files:
        if path.startswith("pyhazards/model_cards/") and path.endswith((".yaml", ".yml")):
            names.add(Path(path).stem)
        if path in source_to_name:
            names.add(source_to_name[path])
    return sorted(name for name in names if name)
